project_id = "vcytcgmqygvqwrbzmmzu"

[functions.question-croisee]
verify_jwt = false

[functions.upload-document]
verify_jwt = false

[functions.list-documents]
verify_jwt = false

[functions.delete-document]
verify_jwt = false

[functions.reindex-documents]
verify_jwt = false

[functions.fix-metadata]
verify_jwt = false